version: "3"

services:

  php:
    build:
      context: Lesson1
      dockerfile: .build/php/Dockerfile
    volumes:
      - "./src:/var/www/html"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'