- name: Install mysql
  become: true
  apt:
    name:
      - mysql-server
    update_cache: yes
    state: latest

- name: Install ansible python3 mysql dependency
  become: true
  apt:
    name: python3-mysqldb
    state: latest

- name: Update mysql root password for all root accounts
  become: true
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create a new database
  become: true
  mysql_db:
    name: testdb
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Add sample data to database
  become: true
  copy:
    src: dump.sql
    dest: /tmp/dump.sql

- name: Insert sample data into database
  become: true
  mysql_db:
    name: testdb
    state: import
    target: /tmp/dump.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"