- hosts: all

  become: true

  vars:
    mysql_root_password: password

  tasks:
    - name: Install mysql
      apt:
        name:
          - mysql-server
        update_cache: yes
        state: latest

    - name: Start up the mysql service
      shell: "Service mysql start"

    - name: Ensure mysql is enables to run on startup
      service:
        name: mysql
        state: started
        enabled: true

    - name: Update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create a new database
      mysql_db:
        name: testdb
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"